classDiagram
    namespace EasySave.Infrastructure.Repositories {
        class JsonConfigRepository {
            +Load(): List~BackupJob~
            +Save(jobs)
        }
        class JsonStateRepository {
            +Update(jobs)
            +Clear(jobs)
            -WriteAtomic(json)
        }
    }

    namespace EasySave.Infrastructure.FileSystem {
        class WindowsFileSystem {
            -CryptoSoftService _crypto
            +CopyFile(source, dest): long
            +CopyAndEncryptFile(source, dest): long
        }
        class CryptoSoftService {
            +Encrypt(source, dest, key): long
        }
    }

    namespace EasySave.Infrastructure.Strategies {
        class FullBackupStrategy {
            +Execute(job, fileSystem, logger, callback)
        }
        class DifferentialBackupStrategy {
            +Execute(job, fileSystem, logger, callback)
            -IsModifiedSince()
        }
    }

    namespace EasySave.Infrastructure.System {
        class WindowsProcessMonitor {
            +IsBusinessSoftwareRunning(processName): bool
        }
    }

    namespace EasySave.Infrastructure.Logging {
        class EasyLogAdapter {
            -IEasyLogWriter _writer
            +Log(entry)
            -MapToDto(entry)
        }
    }

    WindowsFileSystem --> CryptoSoftService : "Utilise (V2.0)"