flowchart LR
    %% Acteurs
    User([Utilisateur])
    OS([Système d'Exploitation])
    Crypto([CryptoSoft.exe])

    %% Système EasySave V2.0
    subgraph EasySave V2.0 - WPF
        UC1(Gérer les travaux de sauvegarde <br> *Illimité*)
        UC2(Exécuter une sauvegarde)
        UC3(Configurer les extensions à crypter)
        UC4(Configurer le logiciel métier)
        
        %% Inclusions (Actions automatiques lors de l'exécution)
        UC5(Détecter le logiciel métier)
        UC6(Crypter les fichiers spécifiques)
        UC7(Générer Log journalier avec CryptoTime)
    end

    %% Relations Utilisateur
    User --> UC1
    User --> UC2
    User --> UC3
    User --> UC4

    %% Relations d'exécution
    UC2 -. "<< include >>" .-> UC5
    UC2 -. "<< include >>" .-> UC6
    UC2 -. "<< include >>" .-> UC7

    %% Relations Acteurs Externes
    OS --- UC5
    Crypto --- UC6